/*
 * Where each component is used, found by reading the source.
 *
 * The gallery is only worth trusting if its numbers are real, and a list of
 * call sites written by hand is wrong within a week. This reads the app
 * files and writes src/component-uses.js, which the gallery imports; a test
 * runs the same scan and fails if the committed file has fallen behind, so
 * it cannot drift quietly.
 *
 *   node scripts/component-uses.mjs          write the file
 *   node scripts/component-uses.mjs --check  report whether it is current
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "src", "component-uses.js");

/* The gallery is left out on purpose: it renders one of everything, so
   counting it would tell you only that the gallery exists. */
const FILES = ["src/shared.jsx", "src/ArabicTrainer.jsx", "src/spaces.jsx"];

/* Comments hold example markup — the library's own doc comments are full of
   <Screen …> — so they have to go before anything is counted. */
function stripComments(source) {
  let out = "";
  let i = 0;
  while (i < source.length) {
    if (source.startsWith("/*", i)) {
      const end = source.indexOf("*/", i + 2);
      const skipped = source.slice(i, end === -1 ? source.length : end + 2);
      /* Newlines are kept so line numbers stay true. */
      out += skipped.replace(/[^\n]/g, " ");
      i = end === -1 ? source.length : end + 2;
    } else if (source.startsWith("//", i)) {
      const end = source.indexOf("\n", i);
      out += " ".repeat((end === -1 ? source.length : end) - i);
      i = end === -1 ? source.length : end;
    } else {
      out += source[i];
      i += 1;
    }
  }
  return out;
}

/* Every component the library exports — the things worth tracking. */
export function libraryComponents() {
  const src = readFileSync(path.join(ROOT, "src/shared.jsx"), "utf8");
  return [...src.matchAll(/^export function ([A-Z]\w*)\s*\(/gm)].map((m) => m[1]).sort();
}

/* A file may rename what it imports: the trainer takes Field as FormField,
   so counting "<Field" there would find nothing at all. */
function localNames(source, components) {
  const map = new Map();
  for (const name of components) map.set(name, name);
  const block = /import\s*\{([\s\S]*?)\}\s*from\s*["']\.\/shared\.jsx["']/.exec(source);
  if (block) {
    for (const part of block[1].split(",")) {
      const m = /^\s*([A-Za-z_]\w*)(?:\s+as\s+([A-Za-z_]\w*))?\s*$/.exec(part);
      if (!m) continue;
      const [, real, alias] = m;
      if (!components.includes(real)) continue;
      if (alias) map.set(alias, real);
    }
  }
  return map;
}

/* The nearest declaration at the left margin: which component the call site
   is inside. Good enough to find the place, and it does not need a parser. */
function enclosing(lines, index) {
  for (let i = index; i >= 0; i--) {
    const m = /^(?:export\s+)?(?:default\s+)?(?:async\s+)?function\s+(\w+)|^(?:export\s+)?const\s+(\w+)\s*=/.exec(lines[i]);
    if (m) return m[1] || m[2];
  }
  return "(top level)";
}

export function scan() {
  const components = libraryComponents();
  const uses = Object.fromEntries(components.map((name) => [name, []]));

  for (const rel of FILES) {
    const raw = readFileSync(path.join(ROOT, rel), "utf8");
    const source = stripComments(raw);
    const lines = source.split("\n");
    const names = localNames(source, components);
    const file = path.basename(rel);

    lines.forEach((line, i) => {
      for (const [local, real] of names) {
        /* An opening tag, and not the start of a longer name: "<Tile" must
           not match "<TileNote". */
        const re = new RegExp(`<${local}(?![A-Za-z0-9_])`, "g");
        for (const _ of line.matchAll(re)) {
          const where = enclosing(lines, i);
          /* A component's own definition is not a use of itself. */
          if (file === "shared.jsx" && where === real) continue;
          uses[real].push({ file, line: i + 1, where, as: local === real ? undefined : local });
        }
      }
    });
  }

  for (const name of components) {
    uses[name].sort((a, b) => a.file.localeCompare(b.file) || a.line - b.line);
  }
  return uses;
}

export function render(uses) {
  const body = Object.entries(uses)
    .map(([name, list]) => {
      const rows = list
        .map((u) => {
          const as = u.as ? `, as: "${u.as}"` : "";
          return `    { file: "${u.file}", line: ${u.line}, where: "${u.where}"${as} },`;
        })
        .join("\n");
      return list.length ? `  ${name}: [\n${rows}\n  ],` : `  ${name}: [],`;
    })
    .join("\n");

  return `/*
 * Generated by scripts/component-uses.mjs — do not edit by hand.
 *
 * Every place each component in shared.jsx is used, with the file, the line
 * and the component it sits inside. The gallery in Admin > App reads this,
 * and tests/component-uses.test.mjs re-runs the scan and fails if this file
 * has fallen behind the source. Regenerate with:
 *
 *   npm run components
 *
 * The gallery itself is not counted: it renders one of everything.
 */
export const COMPONENT_USES = {
${body}
};
`;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const wanted = render(scan());
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(OUT, "utf8");
    } catch (e) {
      current = "";
    }
    if (current !== wanted) {
      console.error("src/component-uses.js is out of date — run: npm run components");
      process.exit(1);
    }
    console.log("src/component-uses.js is current");
  } else {
    writeFileSync(OUT, wanted);
    const uses = scan();
    const total = Object.values(uses).reduce((n, l) => n + l.length, 0);
    console.log(`wrote src/component-uses.js — ${total} uses across ${Object.keys(uses).length} components`);
  }
}
